# Site settings
title: Words by Michelle
subtitle: ""
email: mdeng94@gmail.com
description: "Describing myself is hard"
baseurl: ""
url: "http://mdeng.github.io"
github_username:  "mdeng"
instagram_username: "mdengg"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
